FROM golang:1.10

# Set necessary environmet variables needed for our image
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Move to working directory /build
WORKDIR $GOPATH/src/github.com/shinejoe13/test-code/httpcode

# Copy the code into the container
COPY . .

# Download all the dependencies
RUN go get -d -v ./...

# Install the package
RUN go install -v ./...

# Export necessary port
EXPOSE 3000

# Command to run when starting the container
CMD ["test-code/httpcode"]